print("Datatypes")
a=int(input("Enter an integer:"))
b=float(input("Enter a float:"))
c=str(input("Enter a string:"))
d=bool(input("Enter a boolean value:"))
e=list(input("Enter list of items:"))
print(a," is a ",type(a))
print(b," is a ",type(b))
print(c," is a ",type(c))
print(d," is a ",type(d))
print(e," is a ",type(e))
