print("\tBIO DATA\n")
print("Name: Ramya Krishna")
print("Date of Birth: 1 October 2002")
print("Gender: Female")
print("Address: Thirumangalam,Madurai ")
print("Phone: 6374054419")
print("Email: nrk01102002@gmail.com")
print("Undergraduation: Bachelor of English Literature")
print("Postgraduation: Masters in Computer Application")
print("Skills: Python, HTML, CSS, Javascript, SQL")
print("Hobbies: Singing,Dancing")
print("Language Known: English, Tamil")
print("Nationality: Indian")
