print("*****MY FRIENDS*****\n")
print("1. Malliga")
print("2. Saran")
print("3. Aswitha")
print("4. Haripriya\n")
print("*****MY FAMILY MEMBERS*****\n")
print("Father: Narayana Moorthi")
print("Mother: Sivappu Malli")
print("Brother: Jothi Narayanan")
