print("--------SSLC MARKS--------\n")
print("Tamil: 80")
print("English: 89")
print("Mathematics: 82")
print("Science: 88")
print("Social Science: 90\n")
print("Total: 429\n")
print("--------HSC MARKS--------\n")
print("Tamil: 86")
print("English: 80")
print("Mathematics: 67")
print("Computer Science: 92")
print("Physics: 55")
print("Chemistry: 59\n")
print("Total: 439\n")
print("--------Undergraduation--------\n")
print("English Literature CGPA: 7.3\n")
print("--------Post Graduation--------\n")
print("Computer Applications CGPA: 8.1\n")
