t=(1,2,3,"a","r","d",3.4,5.7)
print("Tuple:",t[:])
print("Reverse:",t[::-1])
print("Pos start index:",t[2:])
print("Pos end index:",t[:5])
print("Pos index range:",t[2:5])
print("Neg start index:",t[-2:])
print("Neg end index:",t[:-5])
print("Neg index range:",t[-5:-2])
